// File: AC42_uw2.v
// Generated by MyHDL 0.11.51
// Date:    Mon Jun 23 02:37:58 2025 UTC


`timescale 1ns/10ps

module AC42_uw2 (
    C,
    S,
    x1,
    x2,
    x3,
    x4
);


output C;
wire C;
output S;
wire S;
input x1;
input x2;
input x3;
input x4;





assign C = ((x1 & x2) | (x3 & x4));
assign S = (((x1 ^ x2) | ((x1 & x2) & (x3 & x4))) | (x3 ^ x4));

endmodule
