/* Generated by Yosys 0.47 (git sha1 647d61dd9, clang++ 16.0.0 -fPIC -O3) */

module EC22(_0_, _1_, _2_, _3_);
  input _0_;
  wire _0_;
  input _1_;
  wire _1_;
  output _2_;
  wire _2_;
  output _3_;
  wire _3_;
  assign _2_ = _1_ & _0_;
  assign _3_ = _1_ ^ _0_;
endmodule
