// File: /Users/fch/Python/OPACT-Extension/General_OPACT_MIP/json2v/ACs/myhdl_EC22.v
// Generated by MyHDL 0.11.51
// Date:    Tue Aug  5 04:46:19 2025 UTC


`timescale 1ns/10ps

module myhdl_EC22 (
    C,
    S,
    x1,
    x2
);
// Compressor 'EC22' (width=2) — SOP form.
// idx mapping: inputs[0] is LSB (pin0) for truth tables.

output C;
wire C;
output S;
wire S;
input x1;
input x2;





assign C = (x1 & x2);
assign S = ((x1 & (~x2)) | ((~x1) & x2));

endmodule
