// File: /Users/fch/Python/OPACT-Extension/General_OPACT_MIP/json2v/ACs/myhdl_EC32.v
// Generated by MyHDL 0.11.51
// Date:    Tue Aug  5 04:46:19 2025 UTC


`timescale 1ns/10ps

module myhdl_EC32 (
    C,
    S,
    x1,
    x2,
    x3
);
// Compressor 'EC32' (width=3) — SOP form.
// idx mapping: inputs[0] is LSB (pin0) for truth tables.

output C;
wire C;
output S;
wire S;
input x1;
input x2;
input x3;





assign C = (((((x1 & x2) & (~x3)) | ((x1 & (~x2)) & x3)) | (((~x1) & x2) & x3)) | ((x1 & x2) & x3));
assign S = (((((x1 & (~x2)) & (~x3)) | (((~x1) & x2) & (~x3))) | (((~x1) & (~x2)) & x3)) | ((x1 & x2) & x3));

endmodule
