// File: /Users/fch/Python/OPACT-Extension/General_OPACT_MIP/json2v/ACs/myhdl_AC32_ew1.v
// Generated by MyHDL 0.11.51
// Date:    Tue Aug  5 04:46:19 2025 UTC


`timescale 1ns/10ps

module myhdl_AC32_ew1 (
    w2,
    w1,
    x1,
    x2,
    x3
);
// Compressor 'AC32_ew1' (width=3) — SOP form.
// idx mapping: inputs[0] is LSB (pin0) for truth tables.

output w2;
wire w2;
output w1;
wire w1;
input x1;
input x2;
input x3;





assign w2 = ((((((x1 & x2) & (~x3)) | (((~x1) & (~x2)) & x3)) | ((x1 & (~x2)) & x3)) | (((~x1) & x2) & x3)) | ((x1 & x2) & x3));
assign w1 = (((((((x1 & (~x2)) & (~x3)) | (((~x1) & x2) & (~x3))) | ((x1 & x2) & (~x3))) | ((x1 & (~x2)) & x3)) | (((~x1) & x2) & x3)) | ((x1 & x2) & x3));

endmodule
